FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENV DATABASE_URL=postgresql+psycopg2://smart_user:smart_password@db:5432/smart_meeting

CMD ["uvicorn", "users_service.main:app", "--host", "0.0.0.0", "--port", "8000"]
